# autoharness installer (generated by auto-mergeinstall agent for AzureNamingTool)
# Reads templates from autoharness home, substitutes variables, writes harness artifacts.
$ErrorActionPreference = 'Stop'

$AUTOHARNESS_HOME = "C:\Users\hannov\AppData\Roaming\uv\tools\autoharness\Lib\site-packages\autoharness\data"
$WS = "c:\Users\hannov\OneDrive - Microsoft\Dev\AzureNamingTool"
$TEMPLATES = Join-Path $AUTOHARNESS_HOME 'templates'

# ---- Variable map ----
$vars = @{}

# Identity / language
$vars['DATE'] = '2026-04-28'
$vars['PROJECT_NAME'] = 'AzureNamingTool'
$vars['PRIMARY_LANGUAGE'] = 'C#'
$vars['PRIMARY_LANGUAGE_LOWER'] = 'csharp'
$vars['LANGUAGE_VERSION'] = '.NET 10.0'
$vars['LANGUAGE_VERSION_DETAIL'] = 'C# / .NET 10.0 (nullable enabled, implicit usings enabled)'
$vars['LANGUAGE_NOTES'] = '(nullable reference types enabled; implicit usings enabled; suppresses CS8602/CS8600/CS1998)'
$vars['LANGUAGE_FILE_GLOB'] = '**/*.cs,**/*.razor'
$vars['DOC_COMMENT_STYLE'] = '/// <summary> XML doc comments'
$vars['UNIMPLEMENTED_MARKER'] = 'throw new NotImplementedException("...");'
$vars['ERROR_PATTERN'] = 'throw typed exceptions; catch and translate at controller boundaries; v2 API returns ApiResponse<T>'
$vars['UNSAFE_POLICY'] = 'No `unsafe` blocks; no reflection-based bypasses of nullability checks; respect `<Nullable>enable</Nullable>`'

# Build / test / lint / format
$vars['BUILD_TOOL'] = 'dotnet'
$vars['BUILD_COMMAND'] = 'dotnet build src/AzureNamingTool.csproj'
$vars['BUILD_CHECK_COMMAND'] = 'dotnet build src/AzureNamingTool.csproj --no-restore'
$vars['TEST_RUNNER'] = 'dotnet test (xunit)'
$vars['TEST_COMMAND'] = 'dotnet test tests/AzureNamingTool.UnitTests/AzureNamingTool.UnitTests.csproj'
$vars['TEST_DIR'] = 'tests/'
$vars['SOURCE_DIR'] = 'src/'
$vars['LINTER'] = 'roslyn analyzers (no external linter)'
$vars['LINT_COMMAND'] = 'dotnet build src/AzureNamingTool.csproj /warnaserror-:CS8602,CS8600,CS1998'
$vars['FORMATTER'] = 'dotnet format'
$vars['FORMAT_COMMAND'] = 'dotnet format src/AzureNamingTool.sln --verify-no-changes'
$vars['FORMAT_CHECK_COMMAND'] = 'dotnet format src/AzureNamingTool.sln --verify-no-changes'
$vars['FORMAT_FIX_COMMAND'] = 'dotnet format src/AzureNamingTool.sln'

# CI / repo
$vars['CI_PLATFORM'] = 'GitHub Actions'
$vars['CI_WORKFLOW_GLOB'] = '**/.github/workflows/*.yml'
$vars['CI_NOTES'] = 'GitHub Actions workflows under .github/workflows/. CI runs build + unit tests on push/PR.'
$vars['POLL_INTERVAL'] = '30'
$vars['MAX_WAIT'] = '900'
$vars['REPO_OWNER'] = 'hannovdm'
$vars['REPO_NAME'] = 'AzureNamingTool'
$vars['DEFAULT_BRANCH'] = 'main'

# Quality gates
$vars['QUALITY_GATE_1_NAME'] = 'build'
$vars['QUALITY_GATE_1'] = 'dotnet build src/AzureNamingTool.csproj'
$vars['QUALITY_GATE_2_NAME'] = 'unit-test'
$vars['QUALITY_GATE_2'] = 'dotnet test tests/AzureNamingTool.UnitTests/AzureNamingTool.UnitTests.csproj'
$vars['QUALITY_GATE_3_NAME'] = 'format-check'
$vars['QUALITY_GATE_3'] = 'dotnet format src/AzureNamingTool.sln --verify-no-changes'
$vars['QUALITY_GATE_4_NAME'] = 'ui-test'
$vars['QUALITY_GATE_4'] = 'dotnet test tests/AzureNamingTool.UiTests/AzureNamingTool.UiTests.csproj'

# Repository operating model
$vars['REPOSITORY_OPERATING_MODEL'] = @'
Azure Naming Tool — ASP.NET Core Blazor Server application (.NET 10.0) for generating
standardized Azure resource names. Layered architecture: Controllers (v1 + v2) → Services
(with `IXxxService` interfaces) → Repositories (`IConfigurationRepository<T>`,
`IStorageProvider`) → JSON files OR SQLite (EF Core, dual storage backend selected via
`StorageProvider` setting in `appsettings.json`). Blazor Components in `src/Components/`
provide the interactive UI. API authentication uses a custom `[ApiKey]` attribute with
three permission tiers. API versioning via `Asp.Versioning` (URL + header). Default seed
data lives in `src/repository/`; runtime config under `src/settings/`. ADRs are kept in
`docs/v5.0.0/adrs/`.
'@

# Project description / structure
$vars['PROJECT_DESCRIPTION'] = 'Azure Naming Tool — generate standardized Azure resource names via Blazor Server UI and v1+v2 REST APIs. Dual storage (FileSystem JSON / SQLite EF Core).'
$vars['PROJECT_STRUCTURE'] = @'
```
src/                       ASP.NET Core Blazor Server app (.NET 10.0)
  Components/              Blazor pages, modals, layout (interactive server-side)
  Controllers/             v1 REST API + V2/ standardized ApiResponse<T>
  Services/                Business logic + Services/Interfaces/IXxxService
  Repositories/            IConfigurationRepository<T>, IStorageProvider
  Models/                  Domain entities + DTOs (ApiResponse<T>, etc.)
  Data/                    EF Core ConfigurationDbContext (SQLite backend)
  Helpers/                 Static utilities (cache, config, validation, file I/O)
  Middleware/              CorrelationId, ApiLogging
  HealthChecks/            Liveness + readiness probes
  Attributes/              ApiKeyAttribute, RateFilter
  repository/              Default seed JSON copied to settings/ on first run
  settings/                Runtime config (JSON) and azurenamingtool.db (SQLite)
  Dockerfile               Container build
  Deployments/AppService-WebApp/  Azure App Service deployment artifacts
tests/
  AzureNamingTool.UnitTests/  xunit + Moq + FluentAssertions
  AzureNamingTool.UiTests/    Playwright + LightBDD + NUnit (net8.0)
docs/v5.0.0/adrs/          Architecture Decision Records
infra/                     Bicep + APIM MCP gateway config
```
'@

# Conventions / rules
$vars['NAMING_CONVENTIONS'] = 'PascalCase for types, members, public properties; camelCase for locals + private fields; `_` prefix for private fields when needed; interfaces prefixed with `I`'
$vars['NAMING_RULES'] = @'
- PascalCase for types, methods, properties, public fields, namespaces
- camelCase for locals, parameters, and private fields (`_camelCase` allowed for private fields)
- Interfaces prefixed with `I` (e.g., `IResourceTypeService`)
- Async methods suffixed with `Async`
- File names match the public type they declare
'@
$vars['CODE_ORGANIZATION_RULES'] = @'
- Layered architecture: Controllers → Services → Repositories → Storage (JSON / SQLite)
- Each service has a matching interface in `Services/Interfaces/IXxxService.cs` and is registered scoped (per-request) in `Program.cs`
- v2 controllers go under `Controllers/V2/` and return `ApiResponse<T>` with correlation IDs
- Razor components: pages in `Components/Pages/`, modals in `Components/Modals/`, shared in `Components/General/` and `Components/Layout/`
- Default seed data in `src/repository/`; runtime config in `src/settings/` (copied on first run)
- ADRs go in `docs/v5.0.0/adrs/`
'@
$vars['ERROR_HANDLING_RULES'] = @'
- Throw typed exceptions; never swallow exceptions silently
- Catch and translate at controller boundaries
- v2 controllers MUST return `ApiResponse<T>` (never raw data) with correlation ID and proper HTTP status (200 / 400 / 401 / 500)
- v1 controllers use the legacy `ServiceResponse` wrapper for backward compatibility
- Log errors via `LogHelper`; never `Console.WriteLine` in production paths
'@
$vars['SAFETY_RULES'] = @'
- `<Nullable>enable</Nullable>` is on; respect nullability annotations
- No `unsafe` code blocks
- No reflection-based bypasses of typing or DI
- All file-system access MUST resolve within the workspace; reject path traversal
- API key validation runs before any authorized action
'@
$vars['PERFORMANCE_RULES'] = @'
- Prefer `async`/`await` for I/O; never block on `.Result` or `.Wait()`
- Use `IAsyncEnumerable<T>` for streaming results when applicable
- Cache configuration data via `CacheHelper` to avoid repeated JSON/SQLite reads
- Avoid LINQ-to-Entities materializing large lists when a count or projection suffices
'@
$vars['TESTING_RULES'] = @'
- Tests live in `tests/AzureNamingTool.UnitTests/` (xunit + Moq + FluentAssertions)
- UI tests live in `tests/AzureNamingTool.UiTests/` (Playwright + LightBDD + NUnit, targets net8.0)
- Test class name mirrors the system-under-test class name (`MyServiceTests`)
- AAA pattern: Arrange / Act / Assert — comments optional but encouraged for non-trivial cases
- Use `Moq` for service collaborators; `FluentAssertions` for readable expectations
- Run a single test with: `dotnet test --filter "FullyQualifiedName~MyTestClass.MyTestMethod"`
'@
$vars['DOCUMENTATION_RULES'] = @'
- XML doc comments (`/// <summary>...</summary>`) on all public types and members
- Inline `<remarks>` for non-obvious behavior; `<exception>` for thrown exception types
- Architecture Decision Records (ADRs) under `docs/v5.0.0/adrs/`
- README and migration guides under `docs/v5.0.0/`
'@
$vars['DEPENDENCY_RULES'] = @'
- Manage NuGet packages in `src/AzureNamingTool.csproj`
- Prefer `Microsoft.*` and well-established community packages
- Pin to compatible major versions; avoid floating wildcards in production builds
- New transitive dependencies require ADR justification when added for runtime use
'@
$vars['ANTI_PATTERNS'] = @'
- Direct file or SQLite access from services — go through `IConfigurationRepository<T>` / `IStorageProvider`
- Returning raw data from v2 controllers — always wrap in `ApiResponse<T>`
- Hard-coding paths — use `appsettings.json` and `ConfigurationHelper`
- Skipping `[ApiKey]` on new API endpoints
- Catching `Exception` then re-throwing without context loss preservation
'@

# Reviewer persona checks
$vars['LANGUAGE_SAFETY_CHECKS'] = @'
- Nullability respected: no unguarded dereference of nullable references
- No `unsafe` blocks introduced
- API endpoints carry `[ApiKey]` (or document why exempt)
- Path-traversal protection on any file-system input
- Secrets never logged or returned in API responses
'@
$vars['LANGUAGE_IDIOM_CHECKS'] = @'
- Services follow the `IXxxService` interface convention and are registered scoped
- Repositories used for storage access (no direct file/db calls from services)
- v2 controllers return `ApiResponse<T>` with correlation ID
- Async methods suffixed `Async`; no `.Result` / `.Wait()` in async paths
- LINQ used idiomatically; no boxing of value types in hot paths
'@
$vars['LANGUAGE_ERROR_HANDLING_CHECKS'] = @'
- Typed exceptions thrown; `Exception` not swallowed
- Controller boundaries translate exceptions to proper HTTP status + `ApiResponse<T>` (v2) or `ServiceResponse` (v1)
- `LogHelper` used; no `Console.WriteLine` in production code paths
- Correlation ID propagated from `IHttpContextAccessor` into log entries
'@
$vars['LANGUAGE_PERFORMANCE_CHECKS'] = @'
- No blocking calls inside async paths (`.Result`, `.Wait()`, `.GetAwaiter().GetResult()`)
- Cache reads via `CacheHelper` for repeated config lookups
- EF Core queries shaped to return only needed fields; no `ToList()` before filtering
- Large enumerations streamed via `IAsyncEnumerable<T>` where applicable
'@
$vars['CONCURRENCY_PATTERNS'] = 'async/await; `IHttpContextAccessor` (per-request); EF Core `DbContext` (scoped); `ConcurrentDictionary` in `CacheHelper`'

# Policies
$vars['LINT_POLICY'] = 'Build with no NEW analyzer warnings. The repo currently suppresses CS8602, CS8600, and CS1998 — do not widen the suppression list without ADR justification.'
$vars['ERROR_HANDLING_POLICY'] = 'All exceptions MUST be typed, logged via `LogHelper`, and translated to proper HTTP responses at controller boundaries. v2 endpoints return `ApiResponse<T>`.'
$vars['ERROR_HANDLING_CONVENTIONS'] = 'Typed exceptions; controller-boundary translation; v2 returns `ApiResponse<T>`; v1 returns legacy `ServiceResponse`.'
$vars['DOCUMENTATION_CONVENTIONS'] = 'XML doc comments on public surfaces; ADRs in `docs/v5.0.0/adrs/` for architecture-level decisions.'
$vars['TEST_STRUCTURE'] = 'Unit tests in `tests/AzureNamingTool.UnitTests/` (xunit); UI tests in `tests/AzureNamingTool.UiTests/` (Playwright + LightBDD + NUnit, net8.0).'
$vars['TEST_TIER_DESCRIPTION'] = 'Unit (xunit + Moq + FluentAssertions) and UI (Playwright + LightBDD + NUnit, net8.0; requires running app).'

# Commit scopes derived from src/ top-level dirs
$vars['COMMIT_SCOPES'] = 'controllers, services, repositories, models, components, helpers, data, middleware, attributes, healthchecks, infra, docs, tests, ci'
$vars['EXAMPLE_SCOPE'] = 'controllers'

# MCP — not an MCP server (set N/A for templates that gate on this)
$vars['MCP_SDK'] = 'N/A (this workspace is not an MCP server)'
$vars['MCP_TRANSPORT'] = 'N/A'
$vars['MCP_PROJECT_STRUCTURE'] = 'N/A — Azure Naming Tool exposes REST APIs (v1 + v2), not an MCP server'

# Additional rows / commands
$vars['ADDITIONAL_STACK_ROWS'] = @'
| Database / Storage | FileSystem (JSON in `src/settings/`) OR SQLite (`settings/azurenamingtool.db` via EF Core) — selected by `StorageProvider` in `appsettings.json` |
| API Versioning | Asp.Versioning (URL + `X-Api-Version` header) |
| Auth | Custom `[ApiKey]` attribute (full / read-only / name-generation tiers) |
| Health Checks | `/health/live`, `/health/ready`, legacy `/healthcheck/ping` |
'@
$vars['ADDITIONAL_COMMANDS'] = @'
- Run the app: `dotnet run --project src/AzureNamingTool.csproj`
- Run a single unit test: `dotnet test tests/AzureNamingTool.UnitTests --filter "FullyQualifiedName~MyTestClass.MyTestMethod"`
- Run UI tests (requires running app): `dotnet test tests/AzureNamingTool.UiTests/AzureNamingTool.UiTests.csproj`
- Format check: `dotnet format src/AzureNamingTool.sln --verify-no-changes`
- Format apply: `dotnet format src/AzureNamingTool.sln`
'@

# Backlog tool — manual mode (no MCP / CLI)
$vars['BACKLOG_TOOL_NAME'] = 'manual'
$vars['BACKLOG_DIRECTORY'] = '.backlog'
$vars['BACKLOG_TOOL_TYPE'] = 'manual'
$vars['BACKLOG_TOOLS'] = 'none (manual file-based backlog)'
$vars['STATUS_QUEUED'] = 'queued'
$vars['STATUS_ACTIVE'] = 'active'
$vars['STATUS_DONE'] = 'done'
$vars['STATUS_BLOCKED'] = 'blocked'
$vars['FIELD_TASK_ID'] = 'id'
$vars['FIELD_TITLE'] = 'title'
$vars['FIELD_STATUS'] = 'status'
$vars['FIELD_LABELS'] = 'labels'
$vars['FIELD_PARENT_ID'] = 'parent_id'
$vars['FIELD_TYPE'] = 'type'
$vars['FIELD_DESCRIPTION'] = 'description'
$vars['FEATURE_SHIPMENTS'] = 'false'
$vars['EXTENDED_OPERATIONS_TABLE'] = '_(no extended operations — manual file-based backlog)_'
foreach ($k in @(
  'OP_CREATE_MCP','OP_LIST_MCP','OP_GET_MCP','OP_UPDATE_MCP','OP_MOVE_MCP','OP_SEARCH_MCP','OP_COMPLETE_MCP',
  'OP_CREATE_CLI','OP_LIST_CLI','OP_GET_CLI','OP_UPDATE_CLI','OP_MOVE_CLI','OP_SEARCH_CLI','OP_COMPLETE_CLI',
  'OP_CREATE_SHIPMENT_MCP','OP_GET_SHIPMENT_MCP','OP_LIST_SHIPMENTS_MCP','OP_CLAIM_SHIPMENT_MCP',
  'OP_SHIP_SHIPMENT_MCP','OP_ADD_TO_SHIPMENT_MCP','OP_RETURN_BLOCKED_MCP',
  'OP_CREATE_CHECKPOINT_MCP','OP_LIST_CHECKPOINTS_MCP','OP_GET_CHECKPOINT_MCP','OP_RESOLVE_CHECKPOINT_MCP',
  'OP_POLL_HOOK_EVENTS_MCP','OP_ACK_HOOK_EVENTS_MCP'
)) { $vars[$k] = '' }

# Suffixes (defaults)
$vars['SUFFIX_FEATURE'] = 'F'
$vars['SUFFIX_CHORE'] = 'C'
$vars['SUFFIX_TASK'] = 'T'
$vars['SUFFIX_SPIKE'] = 'SP'
$vars['SUFFIX_DELIBERATION'] = 'D'
$vars['SUFFIX_BUG'] = 'B'
$vars['SUFFIX_EPIC'] = 'E'
$vars['SUFFIX_SUBTASK'] = 'ST'
$vars['SUFFIX_SHIPMENT'] = 'S'

# Docs paths
$vars['DOCS_ROOT'] = 'docs'
$vars['DOCS_COMPOUND_DIR'] = 'compound'
$vars['DOCS_PLANS_DIR'] = 'plans'
$vars['DOCS_DECISIONS_DIR'] = 'decisions'
$vars['DOCS_MEMORY_DIR'] = 'memory'
$vars['DOCS_CLOSURE_DIR'] = 'closure'
$vars['DOCS_DESIGN_DOCS_DIR'] = 'design-docs'
$vars['DOCS_PRODUCT_SPECS_DIR'] = 'product-specs'
$vars['DOCS_COMPOUND'] = 'docs/compound'
$vars['DOCS_PLANS'] = 'docs/plans'
$vars['DOCS_DECISIONS'] = 'docs/decisions'
$vars['DOCS_MEMORY'] = 'docs/memory'
$vars['DOCS_CLOSURE'] = 'docs/closure'
$vars['DOCS_DESIGN_DOCS'] = 'docs/design-docs'
$vars['DOCS_PRODUCT_SPECS'] = 'docs/product-specs'

# Continuous learning
$vars['CONTINUOUS_LEARNING_DIR'] = '.autoharness/continuous-learning'
$vars['CONTINUOUS_LEARNING_CAPTURE_HOOKS'] = 'false'
$vars['CONTINUOUS_LEARNING_ENVIRONMENT_ADAPTER'] = 'none'
$vars['CONTINUOUS_LEARNING_PROMOTION_THRESHOLD'] = '3'

# Strict safety
$vars['STRICT_SAFETY_ENABLED'] = 'true'

# AI tools
$vars['COPILOT_EXE_PATH'] = 'copilot'

# Model routing tiers
$vars['MODEL_ROUTING_TIER1'] = 'gpt-5.4-mini'
$vars['MODEL_ROUTING_TIER2'] = 'claude-sonnet-4.6'
$vars['MODEL_ROUTING_TIER3'] = 'claude-opus-4.7'

# Composition
$vars['INSTALL_PRESET'] = 'standard'
$vars['PRIMARY_STACK_PACK'] = 'web-app'
$vars['STACK_PACKS_YAML'] = '["web-app", "api-service", "deployable-service"]'
$vars['INSTALL_LAYERS_YAML'] = '["foundation", "instructions", "workflow", "review", "runtime", "backlog", "knowledge", "overlays"]'
$vars['CAPABILITY_PACKS_YAML'] = '["continuous-learning", "strict-safety", "release-observability", "adversarial-review"]'
$vars['HARNESS_OVERRIDES_YAML'] = '{}'

# ---- Substitution function ----
function Expand-Vars([string]$text) {
  return [regex]::Replace($text, '\{\{([A-Z0-9_]+)\}\}', {
    param($m)
    $name = $m.Groups[1].Value
    if ($vars.ContainsKey($name)) { return [string]$vars[$name] }
    return $m.Value  # leave unknown placeholders intact (they are user-fill examples)
  })
}

# ---- Path mapping ----
# Maps a template-relative path under $TEMPLATES to a workspace-relative output path.
function Map-Path([string]$rel) {
  $rel = $rel.TrimStart('\','/')
  $rel = $rel -replace '\\','/'
  # Drop trailing .tmpl
  if ($rel.EndsWith('.tmpl')) { $rel = $rel.Substring(0, $rel.Length - 5) }

  # foundation/AGENTS.md -> AGENTS.md (root)
  if ($rel -eq 'foundation/AGENTS.md') { return 'AGENTS.md' }
  # foundation/copilot-instructions.md -> .github/copilot-instructions.md
  if ($rel -eq 'foundation/copilot-instructions.md') { return '.github/copilot-instructions.md' }
  # foundation/constitution.instructions.md -> .github/instructions/constitution.instructions.md
  if ($rel -eq 'foundation/constitution.instructions.md') { return '.github/instructions/constitution.instructions.md' }

  # harness-config.yaml -> .autoharness/config.yaml
  if ($rel -eq 'harness-config.yaml') { return '.autoharness/config.yaml' }

  # instructions/* -> .github/instructions/*
  if ($rel -like 'instructions/*') { return ".github/$rel" }

  # agents/* -> .github/agents/* (preserves review/, research/ subdirs)
  if ($rel -like 'agents/*') { return ".github/$rel" }

  # skills/* -> .github/skills/*
  if ($rel -like 'skills/*') { return ".github/$rel" }

  # policies/workflow-policies.md -> .github/policies/workflow-policies.md
  if ($rel -like 'policies/*') { return ".github/$rel" }

  # prompts/* -> .github/prompts/*
  if ($rel -like 'prompts/*') { return ".github/$rel" }

  # scripts/* -> scripts/autoharness/*
  if ($rel -like 'scripts/*') {
    $name = $rel.Substring('scripts/'.Length)
    return "scripts/autoharness/$name"
  }

  # backlog/config.yml -> .backlog/config.yml
  if ($rel -eq 'backlog/config.yml') { return '.backlog/config.yml' }
  # backlog/stash.md -> .backlog/.stash.md
  if ($rel -eq 'backlog/stash.md') { return '.backlog/.stash.md' }
  # backlog/registries/* -> NOT installed (read-only by installer)
  if ($rel -like 'backlog/registries/*') { return $null }

  return $null  # unmapped → skip
}

# ---- Walk templates ----
$installed = New-Object System.Collections.Generic.List[string]
$skipped = New-Object System.Collections.Generic.List[string]

Get-ChildItem -Path $TEMPLATES -Recurse -File | ForEach-Object {
  $full = $_.FullName
  $rel = $full.Substring($TEMPLATES.Length + 1)
  $outRel = Map-Path $rel
  if (-not $outRel) {
    $skipped.Add($rel) | Out-Null
    return
  }

  $outFull = Join-Path $WS $outRel
  $outDir = Split-Path $outFull -Parent
  if (-not (Test-Path $outDir)) { New-Item -ItemType Directory -Path $outDir -Force | Out-Null }

  if ($_.Extension -eq '.tmpl') {
    $content = Get-Content -Path $full -Raw -Encoding UTF8
    $expanded = Expand-Vars $content
    Set-Content -Path $outFull -Value $expanded -Encoding UTF8 -NoNewline:$false
  } else {
    Copy-Item -Path $full -Destination $outFull -Force
  }
  $installed.Add($outRel) | Out-Null
}

# ---- Backlog scaffolding (queue + archive dirs) ----
$backlogDirs = @('.backlog/queue', '.backlog/archive')
foreach ($d in $backlogDirs) {
  $p = Join-Path $WS $d
  if (-not (Test-Path $p)) { New-Item -ItemType Directory -Path $p -Force | Out-Null }
  $gk = Join-Path $p '.gitkeep'
  if (-not (Test-Path $gk)) { New-Item -ItemType File -Path $gk -Force | Out-Null }
  $installed.Add("$d/.gitkeep") | Out-Null
}

# ---- Docs scaffolding (knowledge layer) ----
$docDirs = @('docs/compound','docs/plans','docs/decisions','docs/memory','docs/closure','docs/design-docs','docs/product-specs')
foreach ($d in $docDirs) {
  $p = Join-Path $WS $d
  if (-not (Test-Path $p)) { New-Item -ItemType Directory -Path $p -Force | Out-Null }
  $gk = Join-Path $p '.gitkeep'
  if (-not (Test-Path $gk)) { New-Item -ItemType File -Path $gk -Force | Out-Null }
  $installed.Add("$d/.gitkeep") | Out-Null
}

# ---- Continuous-learning scaffolding ----
$clDir = Join-Path $WS '.autoharness/continuous-learning'
if (-not (Test-Path $clDir)) { New-Item -ItemType Directory -Path $clDir -Force | Out-Null }
$clKeep = Join-Path $clDir '.gitkeep'
if (-not (Test-Path $clKeep)) { New-Item -ItemType File -Path $clKeep -Force | Out-Null }
$installed.Add('.autoharness/continuous-learning/.gitkeep') | Out-Null

Write-Host "Installed: $($installed.Count) artifacts" -ForegroundColor Green
Write-Host "Skipped (unmapped): $($skipped.Count)" -ForegroundColor Yellow
$skipped | ForEach-Object { Write-Host "  - $_" }

# Emit installed list for manifest generation
$installed | Sort-Object | Set-Content -Path (Join-Path $WS '.autoharness/installed-artifacts.txt') -Encoding UTF8
